---
- hosts: localhost
  become: true
  gather_facts: no
  tasks:      
  - name: stop if we have old docker container
    command: docker stop simple-devops-container
    ignore_errors: yes

  - name: remove current docker image
    command: docker rmi padrajucs/dockerimage
    ignore_errors: yes

   
  - name: building docker image
    command: docker build -t padrajucs/dockerimage .
    
  - name: creating docker image
    command: docker run --rm -dit --name simple-devops-container -p 9000:8080 padrajucs/dockerimage
    
  - name: push docker image to docker hub
    command: docker push padrajucs/dockerimage
   

